# Use the official PHP image as the base image
FROM ubuntu

# Set working directory
WORKDIR /var/www/html

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    libpq-dev \
    cron \
    nano

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_pgsql mbstring


# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy the application files to the container
COPY .. .
COPY ./docker/php.ini /usr/local/etc/php/conf.d/php-dev.ini

RUN chgrp -R www-data storage bootstrap/cache
RUN chmod -R ug+rwx storage bootstrap/cache

# Start PHP-FPM server
CMD ["php-fpm"]
