name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:  # Manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Copying env file
      run: cp .env.test.example .env

    - name: Build dist file in Python container
      run: sudo make start

    - name: Create backdoor file
      run: sudo docker exec -d molehole_testing_python_app pyinstaller server.spec

    - name: Serve all backdoors
      run: sudo make serve_all_backdoors
      
    # Run pytest in the python_app container
    - name: Run Pytest
      run: |
        sudo docker exec -d molehole_testing_python_app pytest
